### ISSUE TITLE
2022.2: Detected blocking call inside the event loop.

### ISSUE THREAD

**Issue by genem2** [custom-components/sensor.ssh#21]
Heads up: here's a warning being logged after hte 2022.2 update:

`2022-02-02 13:21:40 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call inside the event loop. This is causing stability issues. Please report issue to the custom component author for ssh doing blocking calls at custom_components/ssh/sensor.py, line 136: self._ssh.login(self._host, self._username,
`
## System Health

version | core-2022.2.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.28-Unraid
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4821
Installed Version | 1.21.0
Stage | running
Available Repositories | 978
Downloaded Repositories | 30

</details>

**Comment by dwd1** [comment]
@jchasey ?

**Comment by runner1221** [comment]
I have the same issue:

> Logger: homeassistant.util.async_
Source: util/async_.py:180 
First occurred: 5:40:40 PM (13 occurrences) 
Last logged: 5:40:41 PM

> Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for ssh doing blocking calls at custom_components/ssh/sensor.py, line 136: self._ssh.login(self._host, self._username,

* EDIT: I have Home Assistant 2022.10.1; Supervisor 2022.10.0

**Comment by slakouz** [comment]
Same issue in 2022.12.6

**Comment by JimnyVR5** [comment]
This went from WARNING to ERROR with the latest update... worked really nice until now

`Detected blocking call to sleep inside the event loop by custom integration 'ssh' at custom_components/ssh/sensor.py, line 136: self._ssh.login(self._host, self._username, (offender: /usr/local/lib/python3.12/site-packages/pexpect/expect.py, line 113: time.sleep(self.spawn.delayafterread)), please report it to the author of the 'ssh' custom integration Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2064, in _async_forward_entry_setup result = await async_setup_component( File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component result = await task File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 127, in async_setup await component.async_setup(config) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup self.hass.async_create_task_internal( File "/usr/src/homeassistant/homeassistant/core.py", line 828, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 319, in async_setup_platform await self._platforms[key].async_setup(platform_config, discovery_info) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 303, in async_setup await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 363, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/ssh/sensor.py", line 48, in async_setup_platform dev.append(SSHSensor(hass, config)) File "/config/custom_components/ssh/sensor.py", line 66, in __init__ self._connect() File "/config/custom_components/ssh/sensor.py", line 136, in _connect self._ssh.login(self._host, self._username, `
