### ISSUE TITLE
Stopped working on 2023.6.0b

### ISSUE THREAD

**Issue by jsiemek** [custom-components/sensor.ssh#23]
This usefull component stopped working on HA 2023.6.0b2
Log output:

```Logger: homeassistant.loader
Source: custom_components/ssh/sensor.py:44
Integration: ssh ([documentation](https://github.com/custom-components/sensor.ssh))
First occurred: 12:13:20 (4 occurrences)
Last logged: 12:31:51

Unexpected exception importing platform custom_components.ssh.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/ssh/sensor.py", line 44, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'```

**Comment by Stevehans** [comment]
Guessing this has been abandoned, I'll fix and fork, but it may be better to find something that someone else is supporting going forward

**Comment by Stevehans** [comment]
Quick change in sensors.py

from

```
@asyncio.coroutine
def async_setup_platform(
```

to:-
```
async def async_setup_platform(
```

**Comment by generalk25** [comment]
@Stevehans That fixed it, thank you.

**Comment by deep126** [comment]
@Stevehans easy fix! thank you so much

**Comment by jsiemek** [comment]
@Stevehans thank you very much!
Unfortunately, another error emerged:

Detected blocking call to sleep with args (0.0001,) inside the event loop by custom integration 'ssh' at custom_components/ssh/sensor.py, line 135: self._ssh.login(self._host, self._username, (offender: /usr/local/lib/python3.12/site-packages/pexpect/expect.py, line 113: time.sleep(self.spawn.delayafterread)), please report it to the author of the 'ssh' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2135, in _async_forward_entry_setup result = await async_setup_component( File "/usr/src/homeassistant/homeassistant/setup.py", line 167, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component result = await task File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 123, in async_setup await component.async_setup(config) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 148, in async_setup self.hass.async_create_task_internal( File "/usr/src/homeassistant/homeassistant/core.py", line 830, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 318, in async_setup_platform await self._platforms[key].async_setup(platform_config, discovery_info) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in async_setup await self._async_setup_platform(async_create_setup_awaitable) File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform awaitable = create_eager_task(awaitable, loop=hass.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/config/custom_components/ssh/sensor.py", line 47, in async_setup_platform dev.append(SSHSensor(hass, config)) File "/config/custom_components/ssh/sensor.py", line 65, in __init__ self._connect() File "/config/custom_components/ssh/sensor.py", line 135, in _connect self._ssh.login(self._host, self._username,

Do you have any idea how to approach this?
From log, I know it's not the only custom component having such a problem, iClod3 and better_trhermostatat also face the same problem.
