### ISSUE TITLE
Can no longer restart Home Assistant "Platform error sensor.ssh - Integration 'ssh' not found."

### ISSUE THREAD

**Issue by Rainz3** [custom-components/sensor.ssh#25]
For a little while now I have not been able to restart home assistant due to invalid configuration. I've tried uninstalling Sensor.ssh from hacs but then I get a module not found error. Here is the error below.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 579, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.ssh - Integration 'ssh' not found.
```

EDIT - I was able to figure it out. I had a single entry for SSH in my sensor.yaml file. Commenting it out resolved all issues. Not sure why it broke in the first place though,

**Comment by RNZ01** [comment]
I'm having the same issue now, Could you please provide more details on how you fixed it?
What do you mean by "I had a single entry for SSH in my sensor.yaml file"?
