### ISSUE TITLE
SSH errors and breaking sensors with 2024.7.2

### ISSUE THREAD

**Issue by SeeThisIsMe** [custom-components/sensor.ssh#26]
I hope this is still maintained, or at least someone can point me in the right direction.

I upgraded HA core from 2024.6.4 to 2024.7.2 and since then an SSH sensor I use is broken. I'm getting this error in the logs. Does anyone know what may need to be done here? Thanks!

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:364
integration: Sensor (documentation, issues)
First occurred: July 10, 2024 at 22:10:44 (1 occurrences)
Last logged: July 10, 2024 at 22:10:44

Error while setting up ssh platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/ssh/sensor.py", line 48, in async_setup_platform
    dev.append(SSHSensor(hass, config))
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ssh/sensor.py", line 66, in __init__
    self._connect()
  File "/config/custom_components/ssh/sensor.py", line 136, in _connect
    self._ssh.login(self._host, self._username,
  File "/usr/local/lib/python3.12/site-packages/pexpect/pxssh.py", line 369, in login
    i = self.expect(session_init_regex_array, timeout=login_timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pexpect/spawnbase.py", line 340, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pexpect/expect.py", line 113, in expect_loop
    time.sleep(self.spawn.delayafterread)
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 192, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 158, in raise_for_blocking_call
    raise RuntimeError(
RuntimeError: Caught blocking call to sleep with args (0.0001,) inside the event loop by custom integration 'ssh' at custom_components/ssh/sensor.py, line 136: self._ssh.login(self._host, self._username,. (offender: /usr/local/lib/python3.12/site-packages/pexpect/expect.py, line 113: time.sleep(self.spawn.delayafterread)), please report it to the author of the 'ssh' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep

**Comment by tiran133** [comment]
Just make the platform load synchronously

The package pexpect uses a sleep https://github.com/pexpect/pexpect/blob/master/pexpect/pxssh.py#L228
Wich is called on line 136: self._ssh.login see error message.

This does not work with async anymore.

`ssh/sensors.py`

```python
def setup_platform(hass, config, add_entities, discovery_info=None):

    dev = []
    dev.append(SSHSensor(hass, config))
    add_entities(dev, True)
```

Just remove the async.

**Comment by SeeThisIsMe** [comment]
Nice one, thanks! All good now 😊
