### ISSUE TITLE
Module wont load - pexpect

### ISSUE THREAD

**Issue by grantclem** [custom-components/sensor.ssh#7]
Hi, for some reason the module cannot be found

```
2019-07-03 13:10:25 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform ssh
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/home/homeassistant/.homeassistant/custom_components/ssh/sensor.py", line 48, in async_setup_platform
    dev.append(SSHSensor(hass, config))
  File "/home/homeassistant/.homeassistant/custom_components/ssh/sensor.py", line 66, in __init__
    self._connect()
  File "/home/homeassistant/.homeassistant/custom_components/ssh/sensor.py", line 127, in _connect
    from pexpect import pxssh, exceptions
ModuleNotFoundError: No module named 'pexpect'
```

**Comment by evilgb** [comment]
Same problem here. I also tried "pip3 install pexpect" but it gave the same error.

**Comment by ejonesnospam** [comment]
I had issues with the pexpect library as well, so I created an ssh sensor and switch using the paramiko ssh library. Feel free to try it out.

https://github.com/ejonesnospam/ssh
